id: I26D3C7C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:55:35+00:00'
last_modified: '2022-06-08T06:35:03.040650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26673
  title: གསུང་འབུམ། བརྩོན་འགྲུས་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E9DF:
      image_group_id: I4183
      title: ''
      total_pages: 782
      order: 1
      base_file: E9DF.txt
    '5154':
      image_group_id: I4184
      title: ''
      total_pages: 768
      order: 2
      base_file: 5154.txt
    569B:
      image_group_id: I4185
      title: ''
      total_pages: 758
      order: 3
      base_file: 569B.txt
    26BA:
      image_group_id: I4186
      title: ''
      total_pages: 742
      order: 4
      base_file: 26BA.txt
    43B7:
      image_group_id: I4187
      title: ''
      total_pages: 732
      order: 5
      base_file: 43B7.txt
    77B8:
      image_group_id: I4188
      title: ''
      total_pages: 758
      order: 6
      base_file: 77B8.txt
    FE24:
      image_group_id: I4189
      title: ''
      total_pages: 802
      order: 7
      base_file: FE24.txt
    FFA3:
      image_group_id: I4190
      title: ''
      total_pages: 652
      order: 8
      base_file: FFA3.txt
    35B4:
      image_group_id: I4191
      title: ''
      total_pages: 548
      order: 9
      base_file: 35B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
